"use strict";
let c = 5;
let b = 7;
console.log("test 1");
console.log(c == b);
console.log("test 2");
console.log(c != b);
console.log("test 3");
console.log(b != c);
console.log("test 4");
console.log(c > b);
console.log("test 5");
console.log(c < b);
console.log("test 6");
console.log(b > c);
console.log("test 7");
console.log(b < c);
console.log("test 8");
console.log(c + b > 0);
console.log("test 9");
console.log(c > 0);
console.log("test 10");
console.log(b < 0);
