let firstInstruement="hammer";
let firstCutlery="spoon";
let secondInstruement="screwdriver";
let secondCutlery="fork";
let instuementBox=["Screw","Pillas","Nuts","Hammer"];
console.log("Both are equal");
console.log(firstInstruement==secondInstruement);
console.log("Both are not equal");
console.log(firstCutlery!=secondInstruement);
console.log(firstInstruement.toUpperCase());
let twenty:number=20;
let forty:number=40;
console.log( "both are equal");
console.log(twenty+twenty==forty);
console.log("Both are not equal");
console.log(twenty==forty);
console.log( "both are not equal");
console.log(twenty+twenty!=forty);
console.log("Both are not equal");
console.log(twenty==forty);
console.log("greater than");
console.log(forty>twenty);
console.log(" lessthan");
console.log(20<40);
console.log("greater than or equal to");
console.log(forty>=twenty);
console.log("less than or equal to");
console.log(twenty<=forty);
console.log("And operator");
console.log(twenty<forty&&twenty!=forty);
console.log("or operator");
console.log(twenty==forty||twenty<forty);
console.log("instuement is found in array")
console.log(instuementBox .includes["Hammer"]);
console.log("instuement is not found in an array");
console.log(instuementBox .includes["Scissors"]);
